### ISSUE TITLE
"Parsing error: Identifier 'hash' has already been declared" in App.js

### ISSUE THREAD

**Issue by canaanmerchant** [JoeKarlsson/react-spotify-player#5] opened 2020-01-14 13:55 UTC
I wanted to adapt some of this into an existing project but ran into this issue. I even just used the exact app.js in this project and it returns the same error. Checking the console I see this as well:

> Uncaught Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: C:\Users\cmerchant\Desktop\spotifollowers\src\App.js: Identifier 'hash' has already been declared (81:6)

So I deleted my package-lock.json and node_modules folder and reinstalled but it came back with the same error. I don't have 'hash' declared anywhere else in the file or project and that seems to be the problem when other people have ran into similar errors.

**Comment by JoeKarlsson** [comment] 2020-01-26 19:00
Very strange - I'm guessing it's related to the has.js file included in the app:

https://github.com/JoeKarlsson/react-spotify-player/blob/master/src/hash.js

Have you made any progress on this?

**Comment by JoeKarlsson** [comment] 2020-01-27 18:05
I was not able to reproduce this issue locally. Is anyone else encountering this problem? Can someone provide more context?

**Comment by canaanmerchant** [comment] 2020-01-29 20:47
Sorry, quick update to say I haven't looked at this in a while but now I'm back in it. I do think I made a copy/past error when I was importing hash.js but I actually don't have that. I'm going to need to reset overall and try to start a little simpler .

**Comment by JoeKarlsson** [comment] 2020-01-29 23:38
No worries - dude. It took me a while to respond to your issue. Do you mind if I close this issue? You can open a new one if you run into an error on your refactor. Thank you!

**Closed by JoeKarlsson** 2020-01-29 23:38 UTC
Labels: question
